spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/milestone_mania}
    username: ${DATABASE_USERNAME:milestone_user}
    password: ${DATABASE_PASSWORD:milestone_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.milestonemania: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/milestone-mania.log
